### ISSUE TITLE
Are we ready for 1.0?

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/mime#2]
@christhekeele @allyraza, just let me know if yes or no. :)

**Comment by allyraza** [comment]
I think we should change `path/1` to `from_path/1` it makes much more sense

**Comment by christhekeele** [comment]
I say yes, two nitpicks aside:

1. I've added that README.md usage section without deleting important stuff, and

2. @allyraza I agree. In stdlib `to_` is [common](https://github.com/elixir-lang/elixir/search?utf8=%E2%9C%93&q=%22def+to%22) and `from_` is [rare](https://github.com/elixir-lang/elixir/search?utf8=%E2%9C%93&q=%22def+from%22), but in external libraries that can't inject `to_` versions into modules `from_` is [quite popular](https://github.com/search?utf8=%E2%9C%93&q=%22def+from%22+language%3AElixir+extension%3Aex+path%3A%2Flib&type=Code&ref=advsearch&l=Elixir&l=). AFAIK the only place `MIME.path/1` is ever called is [once in Plug](https://github.com/elixir-lang/plug/blob/03e5efb5b957ecc250455ecaf6bc615187e21234/lib/plug/static.ex#L176), none of the other 4 [library][1] [usages][2] [invoke][3] [it][4], so it could be renamed quite trivially.

I can't think of any other functionality we could add. MIME is a global read-only mapping library. We have the two of the base map read functions, `Map.has_key?/2 => MIME.valid?/1` and `Map.get/3 \\ [] => MIME.extensions/1` and decided against the other two (`Map.keys/1` and `Map.values/1`). We've added an optimized reverse-lookup `MIME.type/1`, and the high-level use-case `MIME.path/1`.

Some part of me wants `extensions/1` and `type/1` to return `:error` like `Map.fetch` rather than a default, but wrapping calls to them with `valid?/1` checks first can simulate this, and makes common usage simpler.

:one::exclamation::zero:
` `` ` :open_hands:
` `` ` :smiley:

[1]: https://github.com/phoenixframework/phoenix/blob/5437165e4e4131a11073a8eb3b1e37755b13fc5b/lib/phoenix/test/conn_test.ex#L317
[2]: https://github.com/phoenixframework/phoenix/blob/0aa855d7458e075cadc7ac1db634f238e501505e/lib/phoenix/controller.ex#L620
[3]: https://github.com/phoenixframework/phoenix/blob/0aa855d7458e075cadc7ac1db634f238e501505e/lib/phoenix/controller.ex#L943
[4]: https://github.com/DockYard/elixir-mail/blob/25fb921804c1f2bf139b452f8f7d1c4cda431919/lib/mail/message.ex#L298
